import streamlit as st
from groq import Groq
import requests

# 1. SETUP & KEYS
GROQ_API_KEY = "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"
HF_TOKEN = "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"

# 2. PAGE CONFIG
st.set_page_config(page_title="Astro AI", page_icon="🚀", layout="wide")

# Sidebar for navigation
with st.sidebar:
    st.title("🚀 Astro AI")
    st.markdown("---")
    mode = st.radio("Choose Mode:", ["💬 Smart Chat", "🎨 Image Studio"])
    st.markdown("---")
    st.info("Powered by Astro AI - Your Multimodal Assistant")

# --- CHAT MODE ---
if mode == "💬 Smart Chat":
    st.header("💬 Astro Chat")
    st.caption("ChatGPT jaisa fast aur aqalmand")
    
    if "messages" not in st.session_state:
        st.session_state.messages = []

    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    if prompt := st.chat_input("Ask Astro anything..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        try:
            client = Groq(api_key=GROQ_API_KEY)
            response = client.chat.completions.create(
                messages=[{"role": "user", "content": prompt}],
                model="llama3-8b-8192",
            )
            full_response = response.choices.message.content
            
            with st.chat_message("assistant"):
                st.markdown(full_response)
            st.session_state.messages.append({"role": "assistant", "content": full_response})
        except Exception as e:
            st.error(f"Chat Error: {e}")

# --- IMAGE MODE ---
else:
    st.header("🎨 Astro Image Studio")
    st.caption("Likhein aur tasveer banayein")
    
    img_prompt = st.text_input("Describe the image you want to create (English):")
    
    if st.button("Generate Art"):
        if img_prompt:
            with st.spinner("Astro is painting your imagination..."):
                try:
                    API_URL = "https://huggingface.co"
                    headers = {"Authorization": f"Bearer {HF_TOKEN}"}
                    response = requests.post(API_URL, headers=headers, json={"inputs": img_prompt})
                    image_bytes = response.content
                    st.image(image_bytes, caption=f"Generated by Astro AI: {img_prompt}")
                except Exception as e:
                    st.error("Image generation mein thora masla aya. Dubara try karein!")
        else:
            st.warning("Pehle kuch describe karein!")
